project_id = "etybjqtfkclugpahsgcj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://etybjqtfkclugpahsgcj.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[edge_functions]
enabled = true

[functions.suggest]
verify_jwt = false

[functions.process-docx]
verify_jwt = false

[functions.generate-tiptap-jwt]
verify_jwt = false