// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etybjqtfkclugpahsgcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0eWJqcXRma2NsdWdwYWhzZ2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNzUzMjEsImV4cCI6MjA3Mjk1MTMyMX0.Z6ZHe-payb1H9whI-VP5Dr12mCWews-5yD_l6cl8yAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});